### ISSUE TITLE
Git issues due to a backup run failure cause all future backups to fail silently

### ISSUE THREAD

**Issue by tedivm** [github/backup-utils#144]
If a repository that is being backed up fails to backup it can be left in an inconsistent state. Since future runs depend on that run (ie, you're running incremental updates and using existing files from previous backups to speed up current ones) it can result in those backups also failing.

Unfortunately this failure is silent- when the ghe-backup script encounters a failed repository is just keeps on going and doesn't output anything. A repository I knew to be 26gb was showing up as 24mb, and after multiple runs there were no errors shown but it continued to not back up that repository.

**Comment by dbussink** [comment]
I have a hard time understanding and reproducing this problem. I suspect there might be some misunderstanding about how hard links work, but I would need more data about the specific repository to be able to answer that question. Let me start first with what I dug into and to explain how this should work (and at least works for me). 

I set up a small instance with a repository with a bunch of random data. I then used `backup-utils` to run backups and deliberately broke / corrupted the backups and then ran new backups. I tried to reproduce corrupt repo's this way in backups that succeeded but I was unable to do so. 

The test repo contained 2MB of random data, after doing two subsequent successful backups, it looked like this:

```
dirkjan@dbussink ~/github/backup-utils/data (master u=) $ du -sk *
2604  20150924T104149
176   20150924T104216
4     current
```

It shows two snapshots, the second one looks a lot smaller on the surface because of how hard links work and how size is reported there. It doesn't report the same file twice when hard linked. If I go into the two directories, you can see they actually do contain all the data:

```
dirkjan@dbussink ~/github/backup-utils/data/20150924T104149 (master u=) $ du -sk
2604	.
```
```
dirkjan@dbussink ~/github/backup-utils/data/20150924T104216 (master u=) $ du -sk
2572	.
```

The next step I did was manually corrupt a `.pack` file in the repository. Normally with `backup-utils` that shouldn't ever be possible, since it uses `rsync` heavily and that only puts file in place when they are successfully synced. 

In the `~/github/backup-utils/data/20150924T104849/repositories/c/nw/c4/ca/42/1/1.git/objects/pack` directory, I did the following:

```
dd if=pack-9679e85606086d99346515be4bf2aeec8cab2626.pack of=pack-9679e85606086d99346515be4bf2aeec8cab2626.pack-new bs=2k count=1k
rm pack-9679e85606086d99346515be4bf2aeec8cab2626.pack
mv pack-9679e85606086d99346515be4bf2aeec8cab2626.pack-new pack-9679e85606086d99346515be4bf2aeec8cab2626.pack
```

This means the repo's pack file is now corrupt. After that I did a new backup with the `20150924T105113` timestamp:

```
~/github/backup-utils/data/20150924T105113/repositories/c/nw/c4/ca/42/1/1.git/objects/pack (BARE:master) $ ls -l
total 4112
-r--r--r--  4 dirkjan  staff     1156 Sep 24 10:23 pack-9679e85606086d99346515be4bf2aeec8cab2626.idx
-r--r--r--  1 dirkjan  staff  2098076 Sep 24 10:23 pack-9679e85606086d99346515be4bf2aeec8cab2626.pack
```

This is again the actual complete file, so `rsync` properly detected the mismatch and updated it. 

Looking at the `du -sk` stats, it now shows the following:

```
Also shows in the du -sk * stats for the snapshots that it redownloaded it:

dirkjan@dbussink ~/github/backup-utils/data (master u=) $ du -sk *
2604  20150924T104149
176   20150924T104216
2256  20150924T104849
2228  20150924T105113
4     current
```

The `20150924T104849` snapshot increased in size because I corrupted the `.pack` file there, which means it could no longer share storage on disk with hard links. Then the new backup is larger again too because we use the `current` snapshot as the base for hard linking and disk space reduction. Since it now again downloaded the proper file, it shows as bigger again.

To further confirm hard link storage is working properly, I ran another backup:

```
du -sk *
2604  20150924T104149
176   20150924T104216
2256  20150924T104849
2228  20150924T105113
176   20150924T105503
4     current
```

This shows the disk space saving again. After this I deleted the `20150924T105113` backup and it shows the following:

```
rm -rf 20150924T105113
du -sk *
2604  20150924T104149
176   20150924T104216
2256  20150924T104849
2228  20150924T105503
```

The `20150924T105503` snapshot not suddenly looks bigger because hard link duplication doesn't work. 

After this I also tested another case where I removed files from an existing backup. This more mimics what could happen with `rsync` if it was aborted. But also in this case, the files I removed were properly present in the next backup. 

I wonder if you would be able to run a similar investigation on your repo that seems to be missing data? Where does the directory structure in the broken backup diverge from the one on the GHE server? Is it in a specific type of files? Ideally a directory structure with file names and sizes of both the backup and GHE server would be best to further debug. 

We use rsync to back up repositories, taking care with timing to prevent git corruption. I find it hard to believe there's a bug in rsync here, so if the backup is silently failing there must be something else weird going on.

**Comment by lildude** [comment]
Closing this issue as stale.
