### ISSUE TITLE
S3 backups do not currently work

### ISSUE THREAD

**Issue by akarnani** [github/backup-utils#148]
The invocation of s3cmd is currently invalid.  Version `1.5.1.2` of `s3cmd` complains `ERROR: Parameter problem: Expecting S3 URI with just the bucket name set instead of 's3://'` from the invocation.

**Comment by brntbeer** [comment]
@akarnani Sorry for the delay, I just ran through the `ghe-s3-backup` command and got a similar issue.

However, you may want to get a newer version of `s3cmd`, this should have been fixed in version `1.6.0`. The commit in question may be https://github.com/s3tools/s3cmd/commit/49966de886f9cebef5dd31bcf252311802f4c641. See it for more details.

Secondly, I also got this error when I didn't have `$GHE_S3_BUCKET` set, @jasonmassey and I are doing some work over in #150 to add that as an item in `backup.config`.

I'm going to close this down, since it may be an issue with version of s3cmd or variable
