### ISSUE TITLE
S3 backups should backup more than just the most recent backup (current)

### ISSUE THREAD

**Issue by akarnani** [github/backup-utils#149]
The S3 scripts only upload/download the current directory.  The upload intends to overwrite all previous data.  However we would find it useful to have the same file structure in S3 as on disk so that we can roll back to arbitrary backups.

We don't trust EBS enough for it to be our sole repository for backups.

**Comment by brntbeer** [comment]
hey @akarnani you should take a look at #150. The new command we're looking to add is `sync` just like yours. 

Since that change uploads just the `current` folder. There will be a change we'll be looking to add afterwards that will probably allow you to pass in a variable to say `--all` and sync the entire data folder.

**Comment by akarnani** [comment]
Seems pretty reasonable to me.  Looking forward to the `--all` change!

**Comment by brntbeer** [comment]
@akarnani totally. good call on using `sync` too (@jasonmassey found it on his own from past experiences too, so it's just me here who's left being new!), it runs **SO** much faster.

**Comment by jasonmassey** [comment]
Closing, should be fixed with #150
