### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ajlanghorn** [github/backup-utils#152]
On the back of https://github.com/github/backup-utils/pull/150, is it possible for a new release to be made? I'd like to back up to S3 rather than to a mounted drive, and would much prefer to use a release than clone from master.

Thanks!

**Comment by carol-hsu** [comment]
Hey, I write one #154 , please give it a try and give me any suggestion :smile:

**Comment by mutle** [comment]
Hi, we're planning to do a release soon. I'll update this issue again when it's :ship:ed...

**Comment by Xeago** [comment]
@mutle could you make sure to have the s3-backup commands in `bin/`?

**Comment by ajlanghorn** [comment]
I agree. But I think a changelog note would be good if and when they're
moved.

On Friday, 29 January 2016, Twan Wolthof <notifications@github.com> wrote:

> @mutle <https://github.com/mutle> could you make sure to have the
> s3-backup commands in bin/?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/backup-utils/issues/152#issuecomment-176965902>
> .
>


-- 
Sent on the move

**Comment by rubiojr** [comment]
@ajlanghorn @Xeago 2.5.0 is out now, including #150. Unfortunately we didn't have time to work on https://github.com/github/backup-utils/pull/154 but we have not discarded working on that at some point and fully/properly support S3 backups/restores.

Closing this since we already have an issue open for the S3 stuff. Thanks!
