### ISSUE TITLE
Compression on Snapshots

### ISSUE THREAD

**Issue by DremonTheCause** [github/backup-utils#259]
Hi,
What is the recommended means of compressing these backup folders? 

Will a tar + gzip of the snapshot folders cause any restoration issues?

Also, for clarification, each backup folder is an independent, complete snapshot of the github host, right? It is not based/dependent on the previous backup right?

**Comment by colossus9** [comment]
Hi @DremonTheCause ,

Wanted to mention our use case to help you in your effort. In our original setup, we were using tar + gzip to ideally compress the backups before going to tape, to reduce the backup footprint. However, when we get into backup sizes of hundreds of GBs, the difference between "tar.gz" and basic "tar" started to become significant. At this point, we decided to accept the larger storage requirement of using non-compressed backups due to (1) the speed of the backups, i.e. in an effort to have more frequent backups in a shorter amount of time and (2) in case of failure, if we need to restore from backup, uncompression would take more time.

Despite this I am really interested to see other's thoughts on the topic.

**Comment by dmittman** [comment]
@DremonTheCause, take a look at [this link](https://github.com/github/backup-utils#backup-snapshot-file-structure), which describes how each backup folder is not, technically, a complete snapshot.

**Comment by lildude** [comment]
@DremonTheCause let me answer your questions in reverse order to give you a good clear picture:

> Also, for clarification, each backup folder is an independent, complete snapshot of the github host, right? It is not based/dependent on the previous backup right?

Each snapshot _is_ technically a complete snapshot of your appliance in as much as you only need to restore one snapshot in order to get a point-in-time restore all your data. 

They are however tied to each other thanks to the use of hard links as backup-utils uses rsync's `--link-dest` option (for example [here](https://github.com/github/backup-utils/blob/1ce68e0002757aeedc09f10b5316f9a4543b3c51/share/github-backup-utils/ghe-backup-userdata#L30-L50)) to reduce the amount of data that is transferred from the appliance and stored on the backup host itself.  Essentially, if the data hasn't changed between snapshots, instead of duplicating the content (waste of bandwidth and space) or just not transferring the file (forces incremental restores) a hard link to the original file in the oldest snapshot is created in the newer snapshot.  Any new or changed file is backed up as normal to the newer snapshot.

This results in quicker subsequent backups that consume significantly less disk space and it's this latter part that I suspect may be partly responsible for your questions.

If you're checking the amount of space each snapshot is using by essentially running something like: `du -hs [snapshot_1] && du -hs [snapshot_2] && du -hs [snapshot_3]` you'll be getting an inaccurate representation and will get the impression each snapshot it taking up way more space than is really the case.

A better and more accurate comparison would to run: `du -hs [snapshot_1] [snapshot_2] [snapshot_3]` which will show only the difference between each snapshot and thus the actual amount of space used by each snapshot.

So knowing the above, we can answer this question...

> Will a tar + gzip of the snapshot folders cause any restoration issues?

No.  If you created a tarball of a single snapshot directory you'd also have a complete backup thanks to tar following the hard links when creating the tarball.  If you created a tarball of all of the snapshot directories, and ensured you maintained hard and symbolic links, you'd have a complete backup of all your incremental backups which you can easily move to a new location, for example if you wanted to setup a new backup host.

This then leads us onto your first question...

> What is the recommended means of compressing these backup folders?

Give the information above, and assuming there hasn't been a significant change on your appliance between snapshots, this question is possibly moot as the only snapshot directory that will be taking up significant amounts of disk space is the oldest in the series of snapshots, confirmed by the `du` command I've suggested. 

Unfortunately, there isn't a good on-disk solution to compress this any further whilst still retaining the structure and the ability to continue with your incremental backups, and easily perform a point-in-time restore, if you need it, short of taking advantage of functionality offered by the underlying storage or filesystem.  For example ZFS and some SAN arrays offer deduplication which could reduce the amount of physical disk space consumed without affecting the appearance of the data to you within the filesystem.

If you're looking to backup the snapshots to something like tape, whilst still keeping the backup times down and the amount of space used on the destination, you're probably best off backing up the entire snapshot directory structure as a whole without compression being sure to retain the hard and symbolic links.

HTH

**Comment by DremonTheCause** [comment]
Wow, thanks @lildude @colossus9.

This was very insightful and thank you for the information.

**Comment by DremonTheCause** [comment]
So based on these responses, it seems like tar.gz compressing each snapshot is not a worthwhile idea. Yet, what about using a rsync with the -archive -compress flags.

I am however still confused about the mechanics of the snapshot system. At what point are snapshots combined into one "main" folder, and then subsequent snapshots folder are produce, and repeat? 

I ask because I was hoping to delete snapshots older than X days, but that doesnt work if after X-1 days they're all combined into a single folder.

Thoughts?

**Comment by michaeltwofish** [comment]
@DremonTheCause You can delete previous snapshots at any time without losing current data.

Snapshots are not "combined", as @lildude explained, they're created using [hard links](https://en.wikipedia.org/wiki/Hard_link). A hard link is a pointer to the data on disk. If multiple snapshots point to the same data, only deleting the _last_ pointer will make the data inaccessible.

You should think about how much historical data you need and consider moving previous snapshots to long-term storage (ie outside of the backup-utils data directory), but you won't risk losing current data by removing previous snapshots.

**Comment by DremonTheCause** [comment]
@michaeltwofish So deleting the oldest/largest folder in the data directory isn't deleting all the data that the hard links reference? 

How can I tell what the last pointer is, or is it different from symlinks?

Also, did the utility create this "backup-old" folder? What's up with that?

Sorry, just very cautious about deleting this data. Thanks

**Comment by michaeltwofish** [comment]
> So deleting the oldest/largest folder in the data directory isn't deleting all the data that the hard links reference?

If another snapshot references the same file, no, deleting the oldest snapshot won't delete the file.

> How can I tell what the last pointer is, or is it different from symlinks?

Here's an explanation of [finding and counting hard links](http://www.giannistsakiris.com/2011/04/15/counting-and-listing-hard-links-on-linux/).

For example, try running `ls -i [snapshot]/audit_log` on different snapshots and you'll see that many of the audit logs reference the same inode (the same data on disk).

> Also, did the utility create this "backup-old" folder? What's up with that?

No, backup-utils didn't create that (unless you set `GHE_DATA_DIR` to that value in your _backup.config_).

**Comment by DremonTheCause** [comment]
Didn't mean to close this LOL

In terms of pruning, is the GHE_NUM_SNAPSHOTS option just deleting individual snapshot "folders" or is actually deleting the data behind the scenes?

The other issue here is whether we are going to run out of space on the machine. 

It seems like the pruning option is deleting snapshots, but other snapshots reference the data, so I'm losing the specific snapshot folder, but still takes up just as much space on disk. Thoughts?

**Comment by DremonTheCause** [comment]
On another note, will rsyncing with excluding symbolic links break the backups? That's the only way I've been able to successfully rsync.

**Comment by michaeltwofish** [comment]
> In terms of pruning, is the GHE_NUM_SNAPSHOTS option just deleting individual snapshot "folders" or is actually deleting the data behind the scenes?

If there are files that are only referenced in the oldest snapshot, and that snapshot is pruned, the files will no longer be accessible (they'll be deleted, for all practical purposes).

> The other issue here is whether we are going to run out of space on the machine.

The [storage requirements section of the README](https://github.com/github/backup-utils#storage-requirements) recommends "allocating at least 5x the amount of storage allocated to the primary GitHub appliance". You should monitor disk space on your backup host and adjust your provisioned storage accordingly.

> It seems like the pruning option is deleting snapshots, but other snapshots reference the data, so I'm losing the specific snapshot folder, but still takes up just as much space on disk.

That's right, if other snapshots reference the same files, disk usage won't change when a snapshot is deleted. You can examine how much space each snapshot is using by running the command @lildude [suggested above](https://github.com/github/backup-utils/issues/259#issuecomment-251890712):

```
du -hs [snapshot_1] [snapshot_2] [snapshot_3]
```

> On another note, will rsyncing with excluding symbolic links break the backups? That's the only way I've been able to successfully rsync.

As [described in the README](https://github.com/github/backup-utils#backup-snapshot-file-structure), symbolic links _cannot_ be excluded. If they are, repositories will be broken when the data is restored to a GitHub Enterprise instance.

**Comment by DremonTheCause** [comment]
So, to effectively use this utility and successfully restore a snapsot, one needs to preserve symlinks and hardlinks in backing up. 

The issue is, I am using Google Cloud Storage (which is object based) for off-site backup. The gsutil -m rsync is the fastest way to upload, but doesnt run because the symlinks point to data that isn't there, so rsync just stops. Excluding symlinks is not an option, so I wanted to use a GCS Fuse, but that doesn't support hardlinks. 

How can I use GCS to backup the data if it is not compatible with both symlinks and hardlink? Has anyone successfully used GCS with this utility?

Thanks!

**Comment by lildude** [comment]
Aaaah, your questions gain a lot more context now we know you're trying to backup to an object-based location.

GCS has the same limitation as S3: you're attempting to use them as a real filesystem when they're not designed to be used as a real filesystem.  Accordingly, you're going to have to compromise on either the amount of data you send each time (lots) or the ability to perform a simple backup-utils point-in-time restore whilst still only transferring changes.

One option would be to create a tarball of each snapshot and upload that each time.  This will give you your point-in-time restores without losing the symlinks but it will mean you're transferring an entire snapshot (many GBs) each time and not just the changes (possibly only MBs).

Another option is to use GCS FUSE as you mentioned but rsync only the "current" snapshot directory and not the entire backup data directory.  This will transfer just the changes from the most recent snapshot but you _will_ lose the ability to perform point-in-time restores from the GCS backups using backup-utils.  Object versioning on the GCS side of things may help you with providing a sort of point-in-time restore though it won't be as easy as the backup-utils provided method.

A third option, which _may_ (I've not tested this) reduce the amount of data transferred and still give you a full backup of the entire backup data directory whilst retaining the symlinks and hardlinks so you can use backup-utils to perform point-in-time snapshot restores as we document, is to use a combination of both of the above by creating a tarball of the entire data directory structure but gzip the data using the `--rsyncable` flag.  You can then rsync this tarball to your GCS FUSE "directory".

The biggest caveat with this last option is time and convenience. In order for this last option to work, you will need to keep using the same filename and you'll need to uncompress the tarball before you can update it (tar can't update compressed tarballs) and then recompress it once you've updated the tarball before syncing it to GCS.

**Comment by DremonTheCause** [comment]
Thanks @lildude 

I have implemented a version of the third option, and all seems well.

I have however ran into an issue where the 'current' symlink is not created/updated after the ghe-backup is run. I know that this block is supposed to do that, and it's doesn't look like a permissions issue.

`if [ -z "$failures" ]; then
    rm "incomplete"

    rm -f "../current"
    ln -s "$GHE_SNAPSHOT_TIMESTAMP" "../current"

    ghe-prune-snapshots
fi`

Any ideas on why this is happening? Is it not created if the snapshot is incomplete?

Thanks!

**Comment by lildude** [comment]
If the symlink isn't being updated it would suggest there has been a failure of sorts prior to that step. Running `ghe-backup -v` should give you a better idea as to why the backup has failed.

**Comment by bloudraak** [comment]
I'm rather interested in the idea of compressing snapshots for different reasons. 

We also need to keep daily backups for six years for compliance reasons.  These backups generally need to be copied to tape and shipped to a secure facility.  A snapshot can also be placed into escrow (which involves copying it once a month to a third party).

A few months ago, we encountered a situation where a repository was reported to be corrupt.  Since folks didn't work much on that repository and some folks joined and left, no one had the "latest" version of the repository on their local machine.   We did not have backups that old and could not restore the repository to a good state, even with all the help of GitHub support.  

As a result, we keep a lot of backups around. This resulted in the dedicated host to run out of inodes after several months of backups.  .The host has a 2T data drive; 1.1TB being used for backups, if "df -h" was to be trusted. We were unable to recover from this since the host became unresponsive and deleting snapshots simply took days.  In the end we formatted the drive and started from scratch. 

In addition to deleting old snapshots, I'd suggest supporting archiving and optionally compress a snapshot.  Disk space isn't an issue for me, but reducing the resource requirements, that is inodes, on the host.  Having a single file is also easier to "ship" to an archive facility or to escrow.

In my case, the host is idling most of the time so there will be no objections running additional processes to archive old snapshots.

**Comment by DremonTheCause** [comment]
Hi guys,
I'm running into some backup trouble now. The GHE-backup script is hanging for over an hour, when the next cron job runs, but aborts. Then so on and so forth: 

bash /backup-utils/bin/ghe-backup -v 1
Error: backup process 238787 of github.intern.weebly.net already in progress in snapshot 20170107T000001. Aborting.

Anyway to diagnose this? If I run it manually it finishes fine. Is it on the scripts end or is it GHE?

Thanks!

**Comment by lildude** [comment]
This is technically a new issue/question so really should be in a new issue. That said, we'd really need to see the process listing/tree associated with the already running backup to workout what is happening.

Try running something like `pstree [pid]` for the PID reported in the message the next time this happens and if it's not clear what the problem is, open a new issue with this data or log a ticket with our Enterprise Support team.
