### ISSUE TITLE
Check target disk space before attempting restore

### ISSUE THREAD

**Issue by adamcharlton** [github/backup-utils#296]
Hi, I encountered an issue where my restore failed due to insufficient disk space on the restore target.

When running the restore on Linux an error like `rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)` occurs however on a Mac you do not get an error at all and it just stalls until you close the restore process.

I think it would be nice if the restore calculated the size of the restore about to happen and verified that the `/data/user` directory on the target had sufficient space for the restore, as this would provide instant feedback that the restore would not be successful.

**Comment by rubiojr** [comment]
@adamcharlton: makes sense. Should be easy to implement for single VM restores.

**Comment by rubiojr** [comment]
@adamcharlton out of curiosity, which macOS/rsync version are you using?

**Comment by rubiojr** [comment]
@adamcharlton we've been discussing this internally. The TL;DR is that estimating if there's enough free disk space available is complicated and/or expensive because we compress some data that has to be expanded remotely. We looking into better error reporting for now, so the cryptic rsync error isn't the only thing you get.

**Comment by shcorbett** [comment]
There has been some work on this recently specifically on the backup side and are looking similarly on restore side -- you can see the release notes on what has been done as part of 3.9 --> https://docs.github.com/en/enterprise-server@3.9/admin/release-notes#3.9.0-backups

Closing out issue here since we are tracking some of this internally.
