### ISSUE TITLE
How take backup locally or same machine where GitHub Enterprise is installed?

### ISSUE THREAD

**Issue by VinodVerma7584** [github/backup-utils#326]
I am not able take backup of GitHub Enterprise locally. I am getting below error message,
"Error: Backup Utils cannot be run on the GitHub Enterprise host.
       The backup utilities should be run on a host dedicated to
       long-term permanent storage and must have network connectivity
       with the GitHub Enterprise appliance."

How could i take backup locally?

**Comment by dbussink** [comment]
The reason we don't allow this is because it's not very useful to backup on the machine itself. It means that the backups are stored on the same machine as where the actual data is stored, so when for example the disk is corrupted, you also lose the backups.

This is why we enforce that you use another server to backup, so that the backed up data is stored independently from the GitHub Enterprise instance and when due to problems the GitHub Enterprise is lost beyond recovery, you don't also lose your backups and have nothing left.

**Comment by VinodVerma7584** [comment]
Thanks for your quick response!
