### ISSUE TITLE
Assumes sha256sum exists as a discrete binary

### ISSUE THREAD

**Issue by tweitzel** [github/backup-utils#336]
backup-utils/share/github-backup-utils/ghe-ssh: line 61: sha256sum: command not found

On freebsd the shasum port installs just /usr/local/bin/shasum, with the expectation that it uses -a 256 to mimic sha256sum.

You can symlink /usr/local/bin/shasum to /usr/local/bin/sha256sum to work around this problem, but the script should not make this assumption and do shasum -a 256 on freebsd.

**Comment by snh** [comment]
Thanks for the report @tweitzel!

https://github.com/github/backup-utils/pull/335, which will ship with the next backup utilities release, fixes this issue by using `git` instead of `sha256sum` to generate the checksum.

In the meantime, you can disable SSH multiplexing, which will remove the dependency on `sha256sum`, by adding `GHE_DISABLE_SSH_MUX=1` to your `backup.config` file.
