### ISSUE TITLE
Implement git version checking and refuse to run if git version is not appropriate

### ISSUE THREAD

**Issue by momcilo78** [github/backup-utils#337]
We had Centos based 1.7 git, which did not have all options used by these tools. This resulted in obscure error message: unknown option: 'literally'.

Please consider checking the version of the tools that these scripts depend on.

**Comment by lildude** [comment]
Whoops. Looks like this was introduced by https://github.com/github/backup-utils/pull/335 (/cc @snh)

An interim solution would be to use the stable branch which still uses sha256sum for the unique ID generation instead of git. This will pose a problem if you use macOS to backup, but it should work on CentOS.

**Comment by momcilo78** [comment]
Actually, our workaround was to upgrade git. I took a while until we figured out with your trainer what was wrong. Having a meaningful message would help avoid confusion ("Please upgrade your git client to at least version x.y").
