### ISSUE TITLE
Restore of Elasticsearch indexes in json form is inoperable on standalone nodes

### ISSUE THREAD

**Issue by terrorobe** [github/backup-utils#457]
The following code will not achieve the desired results for ~two~ reasons

https://github.com/github/backup-utils/blob/e3d505355529e01d06b5e66170641302f6aa70b2/bin/ghe-restore#L301-L309

Firstly, the version check fails due to the included `v` in `$GHE_REMOTE_VERSION`:

```
++ version v2.15.3
++ echo v2.15.3
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
++ version 2.12.9
++ echo 2.12.9
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ '[' 0015003000 -ge 2012009000 ']'
```

~Secondly, the imports are run before `ghe-config-apply` is triggered. This means that all imported data will be written to the ES data directory that is going to be overwritten on the next `ghe-config-apply` invocation.~

~On second reading, the import does not happen during the respective `ghe-restore` scripts but during `ghe-storage-prepare`, so that should work.~

On third reading, the import will not happen because `ghe-storage-prepare` will only `mv` `/data/user/elasticsearch-restore` to `/data/user/elasticsearch`. Importing of the json dumps happens in `elasticsearch-post-start` (systemd `ExecStartPost` for the elasticsearch unit) which only checks `/data/user/elasticsearch-restore`.

Given that the data in the json dumps should be present in the `rsync` backup anyhow I'm inclined to remove the json restore for standalone appliances. The additional json dumps are helpful when trying to recover from corrupted indexes but don't seem to provide any additional value during regular restores.

Thoughts?

**Comment by lildude** [comment]
Nice catch with the version comparison... I suspect I may have missed something, somewhere as I'm pretty sure this did work correctly when I implemented it.

That said, as things stand, neither condition would be true so the JSON dumps won't be restored on single nodes so this is working as you would like by pure luck 😄

**Comment by lildude** [comment]
I've just checked and the version string should _not_ have the `v` in it as it comes from `ghe-negotiate-version` run on the appliance and it does _not_ return the `v`. 

Here's what I get when when I test this against 2.15:

```
$ ghe-negotiate-version backup-utils 2.14.0
GitHub Enterprise version 2.15.3
backup-utils 2.14.0 is supported.
$
```

The first line is what is used for the `$GHE_REMOTE_VERSION` so that makes your first point moot but does make the second relevant.

**Comment by lildude** [comment]
> On third reading, the import will not happen because `ghe-storage-prepare` will only `mv` `/data/user/elasticsearch-restore` to `/data/user/elasticsearch`. Importing of the json dumps happens in `elasticsearch-post-start` (systemd `ExecStartPost` for the elasticsearch unit) which only checks `/data/user/elasticsearch-restore`.

I've only just seen this update. So are you saying this isn't really a problem now?

**Comment by lildude** [comment]
> We're using the output of `ghe-host-check` for `GHE_REMOTE_VERSION`:

Oh yes. Not sure why I thought it was from `ghe-negotiate-version`. It of course brings us back to my original point that the JSON restore would never happen on single nodes then 😄

**Comment by lildude** [comment]
> From my cursory reading it looks like even if we were to copy the compressed json files correctly to the appliance, the files would never be loaded into Elasticsearch.

I've looked into this and once the version issue has been resolved, yes, the JSON files _are_ loaded because they're loaded as part of the restore process itself, for example here for audit logs:

https://github.com/github/backup-utils/blob/e3d505355529e01d06b5e66170641302f6aa70b2/share/github-backup-utils/ghe-restore-es-audit-log#L61-L68

But you're also right in that this is a bit pointless as they'll then be overwritten by exactly the same indices that have been transferred as part of...

https://github.com/github/backup-utils/blob/e3d505355529e01d06b5e66170641302f6aa70b2/bin/ghe-restore#L291-L294

... when `ghe-config-apply` is run, but only if that step actually restored something, which won't be the case if there isn't an `elasticsearch/` directory in the backup.

I'm sure I had a reason for this belt-and-braces approach at the time, but can't think of it right now.

**Comment by lildude** [comment]
> In any case, do you have any objections to removing the version check

Hold off for the moment. I want to try and remember why I implemented it in the first place.

> so that JSON dumps are only restored on cluster?

Other than being a slight waste of time (assuming it worked - fix coming), what problems is this currently causing?

**Comment by terrorobe** [comment]
We've got customers with GiB worth of audit logs due to earlier LDAP-sync over-logging, so for them I assume it will be a quite noticeable waste of time. Not sure how relevant it is in the context of complete restore time though. Hookshot indexes can also be hefty for active appliances. [Numbers from Autodesk](https://enterprise-bundles.github.com/bundles/32495/diagnostics#elasticsearch-indices), as reference.

There's also the topic of correctness, we do some validation that the JSON dumps match the index in question, but at the end of the day the `rsync` copy will always be closer to the actual data on the source server than the data that has been dumped and re-ingested.

**Comment by shcorbett** [comment]
Assuming this issue has been fixed with PRs referenced above - is there anything else outstanding on this? If not, will close this out. Thanks.
