### ISSUE TITLE
[Question] Monitoring scheduled backups

### ISSUE THREAD

**Issue by singhsarab** [github/backup-utils#594]
What is the recommended way to setup scheduled backups for GHES instances?
Are there any recommendations for monitoring whether the scheduled backup is running as expected?

**Comment by djdefi** [comment]
Scheduling and failure notification is generally achieved via crontab on the host running the backup utilities: https://github.com/github/backup-utils/blob/master/docs/scheduling-backups.md

**Comment by singhsarab** [comment]
Can the backup command fail ?
If yes, what are the possible reasons for the backup command to fail and how can we detect that?

Let's say we use crontab and schedule backups, is there a way to know if the cron job is running as expected? and also report failures if any?

**Comment by singhsarab** [comment]
@djdefi We were also considering using Azure's backup functionality, do you know if that be used for restoring ?

**Comment by cainejette** [comment]
Yes @singhsarab I'm sure the backup process can fail -- I would recommend checking cron logs if you are using cron to schedule backups.

**Comment by dgutzmann** [comment]
As an example, you can take advantage of cron emails and pagerduty integration.  If the command returns anything, an email will be sent to the MAILTO address.  Pagerduty has a decent list of features around email integrations.

Since the below is redirecting standard out to a file, the only time an email will be sent is if something is printed to standard err.

```
MAILTO="${UNIQUE PAGERDUTY EMAIL ADDRESS}"

# Job Definition
0 */12 * * *  root  /opt/ghe/backup-utils/bin/ghe-backup -v 1>>/opt/ghe/logs/backup.log
```

**Comment by cainejette** [comment]
Please re-open if you have any other questions related to this.
