### ISSUE TITLE
Permission denied (publickey) when using 2.0.1 in Cygwin

### ISSUE THREAD

**Issue by azzlack** [github/backup-utils#82]
I get `Permission denied (publickey)` when I try to do a `ghe-backup` using v2.0.1.
`ghe-host-check` reports OK, and I am able to ssh into the server using the same key.
It also works fine when using backup-utils v1.1/v2.0 and then entering the ssh key password every time, or using ssh-agent.

Does this have anything to do with Cygwin and batch mode?

**Comment by lildude** [comment]
Yes. The permission denied errors are going to be due to your SSH key containing a passphrase.  backup-utils is written to use batch mode which means it won't prompt you for your passphrase on all of the command invocations. You will need to either use an ssh-agent (preferred) or a passphrase-less key.
