### ISSUE TITLE
Backup snapshot retention

### ISSUE THREAD

**Issue by hemanthecan** [github/backup-utils#823]
In backup.config file even though we have mentioned GHE_NUM_SNAPSHOT=10 we see in the GHE_DATA_DIR=githubdatabackup folder having more than 10 backups its not getting automatically deleted when new backup comes in to the folder this is causing us lot of storage utilization

**Comment by Do-while-Bacon** [comment]
I'm seeing this problem recently too. Never had an issue in the past.

**Comment by jianghao0718** [comment]
Hi @hemanthecan @Do-while-Bacon 
We only prune snapshots when the last backup is successful, see https://github.com/github/backup-utils/blob/ebbef658f1973e34718c91786f8ea6e840fcbb7a/bin/ghe-backup#L248-L255
I am wondering if the latest backups are failing instead. You can ssh to your `$GHE_BACKUP_HOST` and run following command
```
admin@build-dgit-main:~$ journalctl -t backup-utils
-- Logs begin at Mon 2022-01-10 19:53:03 UTC, end at Fri 2022-01-14 22:45:47 UTC. --
Jan 10 23:40:13 build-dgit-main backup-utils[20086]: Starting backup from jianghao0718-r5bbgpwdu.service.bpdev-us-east-1.github.net with backup-utils v3.1.0 in snapshot 20220110T234012 ...
Jan 10 23:40:22 build-dgit-main backup-utils[21857]: Completed backup from jianghao0718-r5bbgpwdu.service.bpdev-us-east-1.github.net / snapshot 20220110T234012 successfully.
```
You should see success message like above instead of something like `Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP with failures: ${steps}.`

Thanks! 🙏

**Comment by Do-while-Bacon** [comment]
@jianghao0718 Looks like backups have been failing since we did the 3.3.1 upgrade. I'm guessing it's because we were still running backup-utils 3.2.0. Fail on my part. I'm usually pretty good about remembering to update the backup utils. 🙄

Hopefully things run smoothly with tonight's backup window.

Thanks!

**Comment by jianghao0718** [comment]
Exactly, `backup-utils` needs to be updated at least matching the major version of GHES. Glad we figured it out!

**Comment by shcorbett** [comment]
Closing out issue as it looks like discussion above points to the issue and next steps. Thanks!
