### ISSUE TITLE
Single repo restore from backup

### ISSUE THREAD

**Issue by sen-kd** [github/backup-utils#914]
Is it possible to restore a single repository from the backup? Like bin/ghe-restore -<reponame> or share/github-backup-utils/ghe-restore-repositories -<reponame> or is there anyother way to achieve this?

Also wanted to know the backup utility version compatability with GHE server version. 

1. Can backup util lower version take backup from Github enterprise server higher version? Example: Can backup util version 3.2.0 take backup from Github enterprise server version 3.3.0? 

2. Can backup util restore data taken from pervious version GHES to higher version of GHES? Example: Can backup util version **3.2.0** restore the backup data taken from GHES v3.1.0 to GHES 3.3.0

**Comment by shcorbett** [comment]
Hi @sen-kd sorry for the very delayed response on this:

> Is it possible to restore a single repository from the backup? Like bin/ghe-restore - or share/github-backup-utils/ghe-restore-repositories - or is there anyother way to achieve this?

We have opened up a customer-feedback issue on this and will look to see if it can be prioritized as part of the product roadmap

> Can backup util lower version take backup from Github enterprise server higher version? Example: Can backup util version 3.2.0 take backup from Github enterprise server version 3.3.0?

We will support up to n-2 versions. Our latest backup-utils version is 3.10 so this can take backups from GHES 3.10, GHES 3.9, and GHES 3.8. You can see the documentation on this here --> https://github.com/github/backup-utils/blob/master/docs/requirements.md#github-enterprise-server-version-requirements


> Can backup util restore data taken from pervious version GHES to higher version of GHES? Example: Can backup util version 3.2.0 restore the backup data taken from GHES v3.1.0 to GHES 3.3.0

When performing backup restores to your GitHub Enterprise Server instance, you can only restore data from at most two feature releases behind. For example, if you take a backup from GitHub Enterprise Server 3.8 you can restore the backup to an instance running GitHub Enterprise Server 3.10. You cannot restore data from a backup of GitHub Enterprise Server 3.7 to an instance running 3.10, because that would be three jumps between versions (3.7 to 3.8 to 3.9 to 3.10). You can see this documentation here --> https://docs.github.com/en/enterprise-server@3.9/admin/backing-up-and-restoring-your-instance/configuring-backups-on-your-instance#restoring-a-backup

Closing out the issue but please post any additional questions you have - thanks!
